'use strict';

// ╔══════════════════════════════════════════════════════════════╗
// ║                    ДАННЫЕ МЕНЮ                               ║
// ║  Все блюда кафе: названия, описания, цены, категории         ║
// ╚══════════════════════════════════════════════════════════════╝

// Заглушка — показывается вместо фото если изображение не загрузилось
const ЗАГЛУШКА_ФОТО = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='300'%3E%3Crect width='400' height='300' fill='%23f2ece0'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' font-size='52' fill='%23c27941'%3E%F0%9F%8D%BD%3C/text%3E%3C/svg%3E";

// Список всех блюд меню
// Каждое блюдо — объект с такими полями:
//   id          — уникальный номер блюда
//   name        — название на русском
//   nameKg      — название на кыргызском
//   description — описание на русском
//   descriptionKg — описание на кыргызском
//   price       — цена в сомах (если нет вариантов)
//   image       — путь к фото
//   category    — категория (shashlik / first / second / special / salad / drink / fastfood / dessert)
//   isHit       — true если это хит продаж
//   ingredients    — ингредиенты на русском (массив)
//   ingredientsKg  — ингредиенты на кыргызском (массив)
//   variants    — варианты блюда (массив с { label, price } или { label, price, image })
//                 если variants есть — поле price не используется

const МЕНЮ = [

  // ══════════════════════════════════════════════════════════════
  //  ШАШЛЫКИ
  // ══════════════════════════════════════════════════════════════
  {
    id: 1, category: 'shashlik', isHit: true,
    name: 'Говядина', nameKg: 'Жылкы эти',
    description: 'Сочный шашлык из говядины на углях',
    descriptionKg: 'Жылкы этинен шашлык, көмүрдө бышырылган',
    price: 260, image: './Меню/Говядинаа.jpeg',
    ingredients: ['Говядина', 'Лук', 'Специи', 'Масло'],
    ingredientsKg: ['Жылкы эти', 'Пияз', 'Азыктар', 'Май'],
  },
  {
    id: 2, category: 'shashlik',
    name: 'Наполеон', nameKg: 'Наполеон',
    description: 'Шашлык Наполеон с нежным вкусом',
    descriptionKg: 'Наполеон шашлык нымдуу даамы менен',
    price: 210, image: './Меню/напалеон.jpeg',
    ingredients: ['Мясо', 'Лук', 'Специи'],
    ingredientsKg: ['Эт', 'Пияз', 'Азыктар'],
  },
  {
    id: 3, category: 'shashlik',
    name: 'Люля-кебаб', nameKg: 'Люля-кебаб',
    description: 'Традиционный люля-кебаб из фарша',
    descriptionKg: 'Фарштан жасалган салттуу люля-кебаб',
    price: 190, image: './Меню/люля.Кебаб.jpeg',
    ingredients: ['Фарш', 'Лук', 'Специи'],
    ingredientsKg: ['Фарш', 'Пияз', 'Азыктар'],
  },
  {
    id: 4, category: 'shashlik',
    name: 'Крылышки шашлык', nameKg: 'Канаттар шашлык',
    description: 'Куриные крылышки на гриле',
    descriptionKg: 'Грилдеги тоок канаттары',
    price: 225, image: './Меню/крылышки.jpeg',
    ingredients: ['Куриные крылышки', 'Специи', 'Масло'],
    ingredientsKg: ['Тоок канаттары', 'Азыктар', 'Май'],
  },
  {
    id: 6, category: 'shashlik',
    name: 'Сет «Компания»', nameKg: '«Компания» сети',
    description: 'Говядина 2, Люля-кебаб 2, Наполеон 2 + подарок',
    descriptionKg: 'Жылкы эти 2, Люля-кебаб 2, Наполеон 2 + белек',
    price: 2050, image: './Меню/Комп.webp',
    ingredients: ['Говядина', 'Люля-кебаб', 'Наполеон'],
    ingredientsKg: ['Жылкы эти', 'Люля-кебаб', 'Наполеон'],
  },
  {
    id: 7, category: 'shashlik',
    name: 'Сет «Фантазия»', nameKg: '«Фантазия» сети',
    description: 'Говядина 2, Люля-кебаб 1, Наполеон 1, Рыба 4, Грибы + подарок',
    descriptionKg: 'Жылкы эти 2, Люля-кебаб 1, Наполеон 1, Балык 4 + белек',
    price: 2800, image: './Menu/Сет фантазия.webp',
    ingredients: ['Говядина', 'Люля-кебаб', 'Наполеон', 'Рыба', 'Грибы'],
    ingredientsKg: ['Жылкы эти', 'Люля-кебаб', 'Наполеон', 'Балык', 'Козу карын'],
  },

  // ══════════════════════════════════════════════════════════════
  //  ПЕРВЫЕ БЛЮДА (Супы)
  // ══════════════════════════════════════════════════════════════
  {
    id: 8, category: 'first',
    name: 'Шорпо (говядина)', nameKg: 'Шорпо (уй эти)',
    description: 'Традиционный суп с говядиной',
    descriptionKg: 'Уй эти менен салттуу шорпо',
    price: 235, image: './Меню/Суп.jpeg',
    ingredients: ['Говядина', 'Картофель', 'Морковь', 'Лук', 'Зелень'],
    ingredientsKg: ['Жылкы эти', 'Картөшкө', 'Сабиз', 'Пияз', 'Жашылча'],
  },
  {
    id: 9, category: 'first',
    name: 'Сырный суп с фрикадельками', nameKg: 'Шорпо фрикаделькалар менен',
    description: 'Сырный суп с фрикадельками и овощами',
    descriptionKg: 'Сыр жана жашылчалар менен суп',
    price: 235, image: './Меню/сыр.jpeg',
    ingredients: ['Сыр', 'Картофель', 'Морковь', 'Лук'],
    ingredientsKg: ['Сыр', 'Картөшкө', 'Сабиз', 'Пияз'],
  },
  {
    id: 10, category: 'first',
    name: 'Суп с фрикадельками', nameKg: 'Фрикаделькалуу суп',
    description: 'Суп с мясными фрикадельками',
    descriptionKg: 'Эт фрикаделькалары менен суп',
    price: 235, image: './Меню/суп с фрикадельками.jpeg',
    ingredients: ['Фрикадельки', 'Картофель', 'Морковь', 'Лук'],
    ingredientsKg: ['Фрикадельки', 'Картөшкө', 'Сабиз', 'Пияз'],
  },
  {
    id: 11, category: 'first',
    name: 'Солянка', nameKg: 'Солянка',
    description: 'Мясная солянка с овощами',
    descriptionKg: 'Жашылчалар менен эт солянкасы',
    price: 205, image: './Меню/солямка.jpeg',
    ingredients: ['Мясо', 'Огурцы', 'Оливки', 'Лук'],
    ingredientsKg: ['Эт', 'Бадыраң', 'Оливки', 'Пияз'],
  },
  {
    id: 12, category: 'first',
    name: 'Пельмени домашние', nameKg: 'Үй пельмени',
    description: 'Домашние пельмени с мясом',
    descriptionKg: 'Эт менен үй пельмени',
    price: 225, image: './Меню/пельмен.jpeg',
    ingredients: ['Тесто', 'Фарш', 'Лук', 'Специи'],
    ingredientsKg: ['Камыр', 'тартылган эт', 'Пияз', 'Азыктар'],
  },
  {
    id: 13, category: 'first',
    name: 'Ак Серке с фрикадельками', nameKg: 'Ак Серке фрикаделькалар менен',
    description: 'Суп Ак Серке с фрикадельками',
    descriptionKg: 'Ак Серке суп фрикаделькалар менен',
    price: 235, image: './Меню/Ак.jpeg',
    ingredients: ['Фрикадельки', 'Картофель', 'Морковь', 'Лук'],
    ingredientsKg: ['Фрикадельки', 'Картөшкө', 'Сабиз', 'Пияз'],
  },
  {
    id: 14, category: 'first',
    name: 'Чечевичный суп', nameKg: 'Чечевичный суп',
    description: 'Суп из чечевицы с овощами',
    descriptionKg: 'Жашылчалар менен чечевица суп',
    price: 195, image: './Меню/Чечч.webp',
    ingredients: ['Чечевица', 'Картофель', 'Морковь', 'Лук'],
    ingredientsKg: ['Чечевица', 'Картөшкө', 'Сабиз', 'Пияз'],
  },

  // ══════════════════════════════════════════════════════════════
  //  ВТОРЫЕ БЛЮДА
  // ══════════════════════════════════════════════════════════════
  {
    id: 15, category: 'second',
    name: 'Манты', nameKg: 'Манты',
    description: 'Паровые манты с мясом',
    descriptionKg: 'Эт менен буу манты',
    price: 240, image: './Меню/манты.jpeg',
    ingredients: ['Тесто', 'Мясо', 'Лук', 'Специи'],
    ingredientsKg: ['Камыр', 'Эт', 'Пияз', 'Азыктар'],
  },
  {
    id: 16, category: 'second',
    name: 'Котлеты', nameKg: 'Котлеталар',
    description: 'Мясные котлеты с гарниром',
    descriptionKg: 'Гарнир менен эт котлеталары',
    price: 220, image: './Меню/Котлетт.jpeg',
    ingredients: ['Фарш', 'Лук', 'Яйцо', 'Хлеб'],
    ingredientsKg: ['тартылган эт', 'Пияз', 'Жумуртка', 'Нан'],
  },
  {
    id: 17, category: 'second',
    name: 'Тефтели', nameKg: 'Тефтель',
    description: 'Мясные тефтели в соусе',
    descriptionKg: 'Соустагы эт тефтель',
    price: 220, image: './Меню/Тефтели.jpeg',
    ingredients: ['Фарш', 'Рис', 'Лук', 'Соус'],
    ingredientsKg: ['Фарш', 'Күрүч', 'Пияз', 'Соус'],
  },
  {
    id: 18, category: 'second',
    name: 'Бифштекс', nameKg: 'Бифштекс',
    description: 'Сочный бифштекс из говядины',
    descriptionKg: 'Жылкы этинен шырындуу бифштекс',
    price: 230, image: './Меню/Зразы.jpeg',
    ingredients: ['Говядина', 'Специи', 'Масло'],
    ingredientsKg: ['Уй эти', 'Азыктар', 'Май'],
  },
  {
    id: 19, category: 'second',
    name: 'Зразы', nameKg: 'Зразы',
    description: 'Мясные зразы с начинкой',
    descriptionKg: 'Начинка менен эт зразы',
    price: 240, image: './Меню/зразымай.jpeg',
    ingredients: ['Мясо', 'Картофель', 'Лук', 'Яйцо'],
    ingredientsKg: ['Эт', 'Картөшкө', 'Пияз', 'Жумуртка'],
  },
  {
    id: 20, category: 'second', isHit: true,
    name: 'Лагман уйгурский', nameKg: 'Уйгур лагманы',
    description: 'Уйгурский лагман с мясом и овощами',
    descriptionKg: 'Эт жана жашылчалар менен уйгур лагманы',
    price: 260, image: './Меню/Лагман уйгур.jpeg',
    ingredients: ['Лапша', 'Мясо', 'Перец', 'Морковь', 'Лук'],
    ingredientsKg: ['Лапша', 'Эт', 'Мурч', 'Сабиз', 'Пияз'],
  },
  {
    id: 21, category: 'second',
    name: 'Лагман жареный', nameKg: 'Куурулган лагман',
    description: 'Жареный лагман с овощами',
    descriptionKg: 'Жашылчалар менен куурулган лагман',
    price: 260, image: './Меню/Лагман жар.webp',
    ingredients: ['Лапша', 'Мясо', 'Перец', 'Морковь', 'Лук'],
    ingredientsKg: ['Лапша', 'Эт', 'Мурч', 'Сабиз', 'Пияз'],
  },
  {
    id: 22, category: 'second',
    name: 'Гуляш', nameKg: 'Гуляш',
    description: 'Гуляш из говядины с овощами',
    descriptionKg: 'Жашылчалар менен жылкы эти гуляш',
    price: 300, image: './Menu/гуляш из говядины.webp',
    ingredients: ['Говядина', 'Картофель', 'Морковь', 'Лук', 'Соус'],
    ingredientsKg: ['Жылкы эти', 'Картөшкө', 'Сабиз', 'Пияз', 'Соус'],
  },
  {
    id: 23, category: 'second',
    name: 'Мясо по-королевски', nameKg: 'Королдук эти',
    description: 'Мясо по-королевски с сыром',
    descriptionKg: 'Сыр менен королдук эт',
    price: 270, image: './Меню/Король.webp',
    ingredients: ['Мясо', 'Сыр', 'Помидоры', 'Зелень'],
    ingredientsKg: ['Эт', 'Сыр', 'Помидор', 'Жашылча'],
  },

  // ══════════════════════════════════════════════════════════════
  //  ЗАКАЗНЫЕ БЛЮДА
  // ══════════════════════════════════════════════════════════════
  {
    id: 24, category: 'special',
    name: 'Мясо по-деревенски (стейк говядина)', nameKg: 'Айылдык эти (стейк)',
    description: 'Стейк говядины по-деревенски',
    descriptionKg: 'Айылдык жылкы эти стейк',
    price: 610, image: './Меню/Дерев.jpeg',
    ingredients: ['Говядина', 'Специи', 'Масло'],
    ingredientsKg: ['Жылкы эти', 'Азыктар', 'Май'],
  },
  {
    id: 25, category: 'special',
    name: 'Стейк форель (3 шт.)', nameKg: 'Форель стейк (3 дөн)',
    description: 'Стейки форели, 3 шт.',
    descriptionKg: 'Форель стейктери, 3 дөн',
    price: 610, image: './Меню/Форель3.jpeg',
    ingredients: ['Форель', 'Специи', 'Масло'],
    ingredientsKg: ['Форель', 'Азыктар', 'Май'],
  },
  {
    id: 26, category: 'special',
    name: 'Стейк форель (2 шт.)', nameKg: 'Форель стейк (2 дөн)',
    description: 'Стейки форели, 2 шт.',
    descriptionKg: 'Форель стейктери, 2 дөн',
    price: 510, image: './Меню/Форель2.jpeg',
    ingredients: ['Форель', 'Специи', 'Масло'],
    ingredientsKg: ['Форель', 'Азыктар', 'Май'],
  },
  {
    id: 27, category: 'special',
    name: 'Адана кебаб', nameKg: 'Адана кебаб',
    description: 'Адана кебаб на шпажках с гарниром и салатом',
    descriptionKg: 'Гарнир жана салат менен шпажкаларда адана кебаб',
    price: 290, image: './Меню/Адана.jpg',
    ingredients: ['Мясо', 'Специи', 'Гарнир', 'Салат'],
    ingredientsKg: ['Эт', 'Азыктар', 'Гарнир', 'Салат'],
  },
  {
    id: 28, category: 'special',
    name: 'Турецкий кебаб', nameKg: 'Түрк кебабы',
    description: 'Турецкий кебаб в лаваше',
    descriptionKg: 'Лавашта түрк кебабы',
    price: 280, image: './Menu/turk.webp',
    ingredients: ['Мясо', 'Лаваш', 'Овощи'],
    ingredientsKg: ['Эт', 'Лаваш', 'Жашылчалар'],
  },
  {
    id: 29, category: 'special',
    name: 'Бейти кебаб', nameKg: 'Бейти кебаб',
    description: 'Бейти кебаб в лаваше с плавленым сыром',
    descriptionKg: 'Лавашта эритилген сыр менен бейти кебаб',
    price: 330, image: './Меню/Бейти кебаб.jpeg',
    ingredients: ['Мясо', 'Лаваш', 'Сыр'],
    ingredientsKg: ['Эт', 'Лаваш', 'Сыр'],
  },
  {
    id: 30, category: 'special',
    name: 'Лазуро', nameKg: 'Лазуро',
    description: 'Жареное мясо с овощами',
    descriptionKg: 'Жашылчалар менен куурулган эт',
    price: 280, image: './Меню/лаз.jpeg',
    ingredients: ['Мясо', 'Овощи', 'Масло'],
    ingredientsKg: ['Эт', 'Жашылчалар', 'Май'],
  },
  {
    id: 31, category: 'special',
    name: 'Бризоль', nameKg: 'Бризоль',
    description: 'Бризоль из мяса',
    descriptionKg: 'Эттен бризоль',
    price: 265, image: './Меню/Бризоль.jpg',
    ingredients: ['Мясо', 'Специи', 'Масло'],
    ingredientsKg: ['Эт', 'Азыктар', 'Май'],
  },
  {
    id: 32, category: 'special',
    name: 'Мясо в горшочке', nameKg: 'Кыштектеги эт',
    description: 'Мясо в горшочке с помидорами, грибами и сыром',
    descriptionKg: 'Помидор, козу карын жана сыр менен кыштектеги эт',
    price: 290, image: './Меню/Мясо в горшочке.jpeg',
    ingredients: ['Мясо', 'Помидоры', 'Грибы', 'Сыр'],
    ingredientsKg: ['Эт', 'Помидор', 'Козу карын', 'Сыр'],
  },
  {
    id: 33, category: 'special',
    name: 'Куурдак', nameKg: 'Куурдак',
    description: 'Куурдак из говядины и баранины',
    descriptionKg: 'Жылкы эти жана кой этинен куурдак',
    price: 490, image: './Меню/Куурдак.jpeg',
    ingredients: ['Говядина', 'Баранина', 'Картофель', 'Лук'],
    ingredientsKg: ['Жылкы эти', 'Кой эти', 'Картөшкө', 'Пияз'],
  },
  {
    id: 34, category: 'special',
    name: 'Курица в кисло-сладком соусе', nameKg: 'Кышкыл-таттуу соустагы тоок',
    description: 'Курица в кисло-сладком соусе',
    descriptionKg: 'Кышкыл-таттуу соустагы тоок',
    price: 290, image: './Меню/кисло.png',
    ingredients: ['Курица', 'Соус', 'Овощи'],
    ingredientsKg: ['Тоок', 'Соус', 'Жашылчалар'],
  },
  {
    id: 35, category: 'special',
    name: 'Фрикассе', nameKg: 'Фрикассе',
    description: 'Фрикассе из курицы',
    descriptionKg: 'Тооктон фрикассе',
    price: 290, image: './Меню/Фрикассе.jpeg',
    ingredients: ['Курица', 'Сливки', 'Овощи'],
    ingredientsKg: ['Тоок', 'Каймак', 'Жашылчалар'],
  },
  {
    id: 36, category: 'special',
    name: 'Мясо фирменное', nameKg: 'Фирмалык эт',
    description: 'Фирменное мясо кафе Cholpon',
    descriptionKg: 'Фирмалык эт',
    price: 460, image: './Menu/фирменное мясо.webp',
    ingredients: ['Мясо', 'Специи', 'Соус'],
    ingredientsKg: ['Эт', 'Азыктар', 'Соус'],
  },
  {
    id: 37, category: 'special',
    name: 'Плов 1 кг', nameKg: 'Плов 1 кг',
    description: 'Плов 1 кг, заказ заранее',
    descriptionKg: 'Плов 1 кг, алдын ала заказ',
    price: 2200, image: './Меню/Пловв.jpeg',
    ingredients: ['Рис', 'Мясо', 'Морковь', 'Лук', 'Специи'],
    ingredientsKg: ['Күрүч', 'Эт', 'Сабиз', 'Пияз', 'Азыктар'],
  },
  {
    id: 38, category: 'special',
    name: 'Казан кебаб', nameKg: 'Казан кебабы',
    description: 'Казан кебаб',
    descriptionKg: 'Казан кебабы',
    price: 320, image: './Меню/Казан.jpeg',
    ingredients: ['Мясо', 'Картофель', 'Лук', 'Специи'],
    ingredientsKg: ['Эт', 'Картөшкө', 'Пияз', 'Азыктар'],
  },
  {
    id: 39, category: 'special',
    name: 'Хачапури', nameKg: 'Хачапури',
    description: 'Хачапури с сыром',
    descriptionKg: 'Сыр менен хачапури',
    price: 460, image: './Меню/хачапури.jpeg',
    ingredients: ['Тесто', 'Сыр', 'Масло'],
    ingredientsKg: ['Камыр', 'Сыр', 'Май'],
  },
  {
    id: 40, category: 'special',
    name: 'Фетучини с курицей', nameKg: 'Тоок менен фетучини',
    description: 'Фетучини с курицей',
    descriptionKg: 'Тоок менен фетучини',
    price: 390, image: './Меню/Фетучини.webp',
    ingredients: ['Фетучини', 'Курица', 'Сливки', 'Сыр'],
    ingredientsKg: ['Фетучини', 'Тоок', 'Каймак', 'Сыр'],
  },

  // ══════════════════════════════════════════════════════════════
  //  САЛАТЫ
  // ══════════════════════════════════════════════════════════════
  {
    id: 41, category: 'salad',
    name: 'Греческий', nameKg: 'Грек',
    description: 'Греческий салат с маслом',
    descriptionKg: 'Май менен грек салаты',
    price: 225, image: './Меню/Грек.webp',
    ingredients: ['Помидоры', 'Огурцы', 'Сыр фета', 'Масло'],
    ingredientsKg: ['Помидор', 'Бадыраң', 'Фета сыры', 'Май'],
  },
  {
    id: 42, category: 'salad',
    name: 'Столичный', nameKg: 'Борбордук',
    description: 'Столичный салат с мясом',
    descriptionKg: 'Эт менен борбордук салат',
    price: 250, image: './Меню/столичный.png',
    ingredients: ['Мясо', 'Корнишоны', 'Грибы', 'Лук', 'Масло'],
    ingredientsKg: ['Эт', 'Корнишон', 'Козу карын', 'Пияз', 'Май'],
  },
  {
    id: 43, category: 'salad',
    name: 'Восточный', nameKg: 'Чыгыштык',
    description: 'Восточный салат с овощами и мясом',
    descriptionKg: 'Жашылчалар жана эт менен чыгыштык салат',
    price: 250, image: './Меню/Вост.jpeg',
    ingredients: ['Помидоры', 'Огурцы', 'Мясо', 'Лук', 'Кабачки', 'Баклажан'],
    ingredientsKg: ['Помидор', 'Бадыраң', 'Эт', 'Пияз', 'Кабачки', 'Баклажан'],
  },
  {
    id: 44, category: 'salad',
    name: 'Китайский острый', nameKg: 'Кытайлык ачтуу',
    description: 'Острый китайский салат',
    descriptionKg: 'Ачтуу кытай салаты',
    price: 240, image: './Меню/Кит ос.jpeg',
    ingredients: ['Помидоры', 'Огурцы', 'Мясо', 'Лук', 'Морковь', 'Перец'],
    ingredientsKg: ['Помидор', 'Бадыраң', 'Эт', 'Пияз', 'Сабиз', 'Мурч'],
  },
  {
    id: 45, category: 'salad',
    name: 'Гасконский', nameKg: 'Гаскон',
    description: 'Гасконский салат с копченой окорочкой',
    descriptionKg: 'Копченка менен гаскон салаты',
    price: 230, image: './Меню/Гасконгский.jpeg',
    ingredients: ['Помидоры', 'Корнишоны', 'Опята', 'Копченая окорочка'],
    ingredientsKg: ['Помидор', 'Корнишон', 'Опята', 'Копченка'],
  },
  {
    id: 46, category: 'salad',
    name: 'Витаминка', nameKg: 'Витаминка',
    description: 'Витаминный салат с овощами',
    descriptionKg: 'Жашылчалар менен витамин салат',
    price: 195, image: './Меню/Витаминка.webp',
    ingredients: ['Свекла', 'Колбаска', 'Кукуруза', 'Зелень', 'Морковь'],
    ingredientsKg: ['Кызылча', 'Колбаса', 'Жүгөрү', 'Жашылча', 'Сабиз'],
  },
  {
    id: 47, category: 'salad',
    name: 'Овощной микс', nameKg: 'Жашылча микси',
    description: 'Микс овощного салата',
    descriptionKg: 'Жашылча салат микси',
    price: 235, image: './Меню/Микс овощщ.jpeg',
    ingredients: ['Цветная капуста', 'Брокколи', 'Овощи'],
    ingredientsKg: ['Түстүү капуста', 'Брокколи', 'Жашылчалар'],
  },
  {
    id: 48, category: 'salad',
    name: 'Свежий', nameKg: 'Жаңы',
    description: 'Свежий овощной салат',
    descriptionKg: 'Жаңы жашылча салаты',
    price: 130, image: './Меню/Свежий.webp',
    ingredients: ['Помидоры', 'Огурцы', 'Лук', 'Масло'],
    ingredientsKg: ['Помидор', 'Бадыраң', 'Пияз', 'Май'],
  },
  {
    id: 49, category: 'salad',
    name: 'Фунчоза', nameKg: 'Фунчоза',
    description: 'Салат с фунчозой, мясом и овощами',
    descriptionKg: 'Фунчоза, эт жана жашылчалар менен салат',
    price: 230, image: './Меню/Фун.webp',
    ingredients: ['Мясо', 'Овощи', 'Фунчоза'],
    ingredientsKg: ['Эт', 'Жашылчалар', 'Фунчоза'],
  },
  {
    id: 50, category: 'salad',
    name: 'Нарезка фирменная', nameKg: 'Фирмалык нарезка',
    description: 'Фирменная овощная нарезка',
    descriptionKg: 'Фирмалык жашылча нарезкасы',
    price: 350, image: './Меню/Фирма.jpeg',
    ingredients: ['Огурцы', 'Помидоры', 'Квашеная капуста', 'Лук'],
    ingredientsKg: ['Бадыраң', 'Помидор', 'Кычкыл капуста', 'Пияз'],
  },
  {
    id: 51, category: 'salad',
    name: 'Воздушный', nameKg: 'Аба',
    description: 'Воздушный салат с майонезом',
    descriptionKg: 'Майонез менен аба салат',
    price: 220, image: './Меню/Воздух.jpeg',
    ingredients: ['Басай', 'Яйцо', 'Чипсы', 'Майонез'],
    ingredientsKg: ['Басай', 'Жумуртка', 'Чипсы', 'Майонез'],
  },
  {
    id: 52, category: 'salad',
    name: 'Цезарь с курицей', nameKg: 'Тоок менен Цезарь',
    description: 'Цезарь с курицей',
    descriptionKg: 'Тоок Цезарь',
    price: 245, image: './Меню/Цезарь  .jpeg',
    ingredients: ['Курица', 'Салат', 'Сыр', 'Крутоны', 'Майонез'],
    ingredientsKg: ['Тоок', 'Салат', 'Сыр', 'Крутон', 'Майонез'],
  },
  {
    id: 53, category: 'salad',
    name: 'Гнездо кукушки', nameKg: 'Кукушка уясы',
    description: 'Гнездо кукушки с майонезом',
    descriptionKg: 'Майонез менен кукушка уясы',
    price: 240, image: './Меню/Гнездо-кукушки.jpeg',
    ingredients: ['Копченое мясо', 'Пай', 'Кукуруза', 'Сыр', 'Майонез'],
    ingredientsKg: ['Копченка', 'Пай', 'Жүгөрү', 'Сыр', 'Майонез'],
  },
  {
    id: 54, category: 'salad',
    name: 'Мерло', nameKg: 'Мерло',
    description: 'Мерло салат с майонезом',
    descriptionKg: 'Майонез менен мерло салат',
    price: 210, image: './Меню/Мерлоо.jpeg',
    ingredients: ['Омлет', 'Горох', 'Кукуруза', 'Курица', 'Майонез'],
    ingredientsKg: ['Омлет', 'Буурчак', 'Жүгөрү', 'Тоок', 'Майонез'],
  },
  {
    id: 55, category: 'salad',
    name: 'Салат с грибами', nameKg: 'Козу карын менен салат',
    description: 'Салат с грибами и майонезом',
    descriptionKg: 'Майонез менен козу карын салат',
    price: 245, image: './Меню/Салат с грибами.jpeg',
    ingredients: ['Шампиньоны', 'Филе', 'Яйцо', 'Картофель пай', 'Майонез'],
    ingredientsKg: ['Шампиньон', 'Филе', 'Жумуртка', 'Картөшкө пай', 'Майонез'],
  },
  {
    id: 56, category: 'salad',
    name: 'Салат со свеклой', nameKg: 'Кызылча менен салат',
    description: 'Салат со свеклой и майонезом',
    descriptionKg: 'Майонез менен кызылча салат',
    price: 235, image: './Menu/Салат со свеклой.webp',
    ingredients: ['Свекла', 'Брокколи', 'Творожный сыр', 'Орех', 'Майонез'],
    ingredientsKg: ['Кызылча', 'Брокколи', 'Творожный сыр', 'Орех', 'Майонез'],
  },
  {
    id: 57, category: 'salad',
    name: 'Охотница', nameKg: 'Охотница',
    description: 'Охотница салат с майонезом',
    descriptionKg: 'Майонез менен охотница салат',
    price: 250, image: './Меню/Охотникк.jpeg',
    ingredients: ['Охотница', 'Корнишоны', 'Черри', 'Шампиньоны', 'Орешки', 'Майонез'],
    ingredientsKg: ['Охотница', 'Корнишон', 'Черри', 'Шампиньон', 'Орех', 'Майонез'],
  },
  {
    id: 58, category: 'salad',
    name: 'Баклажан с овощами', nameKg: 'Жашылчалуу баклажан',
    description: 'Баклажан с овощами и майонезом',
    descriptionKg: 'Майонез менен жашылчалуу баклажан',
    price: 255, image: './Меню/Бакл-овощ.jpeg',
    ingredients: ['Баклажаны', 'Перец', 'Помидоры', 'Лук', 'Майонез'],
    ingredientsKg: ['Баклажан', 'Мурч', 'Помидор', 'Пияз', 'Майонез'],
  },
  {
    id: 59, category: 'salad',
    name: 'Фирменный баклажан', nameKg: 'Фирмалык баклажан',
    description: 'Фирменный баклажан в панировке',
    descriptionKg: 'Панировкадагы фирмалык баклажан',
    price: 255, image: './Menu/Баклажан в панировке.webp',
    ingredients: ['Баклажан', 'Панировка', 'Майонез'],
    ingredientsKg: ['Баклажан', 'Панировка', 'Майонез'],
  },
  {
    id: 60, category: 'salad',
    name: 'Баклажан микс', nameKg: 'Баклажан микси',
    description: 'Микс баклажанов с майонезом',
    descriptionKg: 'Майонез менен баклажан микси',
    price: 240, image: './Меню/МикссБакл.jpeg',
    ingredients: ['Баклажан', 'Майонез'],
    ingredientsKg: ['Баклажан', 'Майонез'],
  },
  {
    id: 61, category: 'salad',
    name: 'Курица с овощами', nameKg: 'Жер жемиштери менен тоок',
    description: 'Курица с ореховым соусом',
    descriptionKg: 'Орех соусу менен тоок',
    price: 240, image: './Меню/Кура.webp',
    ingredients: ['Курица', 'Ореховый соус', 'Майонез'],
    ingredientsKg: ['Тоок', 'Орех соусу', 'Майонез'],
  },

  // ══════════════════════════════════════════════════════════════
  //  НАПИТКИ (с вариантами объёма)
  // ══════════════════════════════════════════════════════════════
  {
    id: 62, category: 'drink',
    name: 'Компот', nameKg: 'Компот',
    description: 'Компот из сухофруктов',
    descriptionKg: 'Куру жемиштерден компот',
    image: './Меню/Компот.webp',
    variants: [
      { label: '1 л',   price: 100 },
      { label: '1.5 л', price: 140 },
      { label: '2 л',   price: 170 },
    ],
  },
  {
    id: 63, category: 'drink',
    name: 'Кола', nameKg: 'Кола',
    description: 'Coca-Cola',
    descriptionKg: 'Кола',
    image: './Меню/Кола.webp',
    variants: [
      { label: '1 л',   price: 120 },
      { label: '1.5 л', price: 170 },
      { label: '2 л',   price: 200 },
    ],
  },
  {
    id: 64, category: 'drink',
    name: 'Фанта', nameKg: 'Фанта',
    description: 'Fanta',
    descriptionKg: 'Фанта',
    image: './Меню/Фанта.webp',
    variants: [
      { label: '1 л',   price: 120 },
      { label: '1.5 л', price: 170 },
      { label: '2 л',   price: 200 },
    ],
  },
  {
    id: 85, category: 'drink',
    name: 'Лимонад', nameKg: 'Лимонад',
    description: 'Освежающий домашний лимонад',
    descriptionKg: 'Сергитүүчү үй лимонады',
    image: './Меню/лимонад.webp',
    variants: [
      { label: '1 л',   price: 120 },
      { label: '1.5 л', price: 160 },
      { label: '2 л',   price: 200 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  //  ФАСТ-ФУД
  // ══════════════════════════════════════════════════════════════
  {
    id: 66, category: 'fastfood',
    name: 'Стрипсы корейские', nameKg: 'Корей стрипсы',
    description: 'Корейские куриные стрипсы',
    descriptionKg: 'Корей тоок стрипсы',
    price: 290, image: './Меню/Стрипсы кор.jpeg',
    ingredients: ['Курица', 'Специи', 'Масло'],
    ingredientsKg: ['Тоок', 'Азыктар', 'Май'],
  },
  {
    id: 67, category: 'fastfood',
    name: 'KFC + фри', nameKg: 'KFC + фри',
    description: 'Курица KFC с картошкой фри',
    descriptionKg: 'KFC тоок фри картөшкө менен',
    image: './Меню/Картошка.webp',
    variants: [
      { label: '20 шт', price: 310 },
      { label: '10 шт', price: 260 },
    ],
  },
  {
    id: 69, category: 'fastfood',
    name: 'Шаурма с курицей', nameKg: 'Тоок менен шаурма',
    description: 'Шаурма с курицей',
    descriptionKg: 'Тоок менен шаурма',
    price: 260, image: './Меню/Шаурма.jpeg',
    ingredients: ['Лаваш', 'Курица', 'Овощи', 'Соус'],
    ingredientsKg: ['Лаваш', 'Тоок', 'Жашылчалар', 'Соус'],
  },
  {
    id: 71, category: 'fastfood', isHit: true,
    name: 'Пицца «Пепперони»', nameKg: 'Пицца «Пепперони»',
    description: 'Пицца Пепперони',
    descriptionKg: 'Пепперони пиццасы',
    image: './Меню/пиццапеп.png',
    ingredients: ['Тесто', 'Сыр', 'Пепперони', 'Соус'],
    ingredientsKg: ['Камыр', 'Сыр', 'Пепперони', 'Соус'],
    variants: [
      { label: '30 см', price: 550 },
      { label: '40 см', price: 750 },
    ],
  },
  {
    id: 72, category: 'fastfood',
    name: 'Пицца «Мясная»', nameKg: 'Пицца «Эттүү»',
    description: 'Мясная пицца',
    descriptionKg: 'Эттүү пицца',
    image: './Меню/Мясо.webp',
    ingredients: ['Тесто', 'Сыр', 'Мясо', 'Соус'],
    ingredientsKg: ['Камыр', 'Сыр', 'Эт', 'Соус'],
    variants: [
      { label: '30 см', price: 590 },
      { label: '40 см', price: 790 },
    ],
  },
  {
    id: 73, category: 'fastfood',
    name: 'Пицца «Курица с грибами»', nameKg: 'Пицца «Тоок козу карын»',
    description: 'Пицца с курицей и грибами',
    descriptionKg: 'Тоок жана козу карын менен пицца',
    image: './Меню/Пицца с гриб.webp',
    ingredients: ['Тесто', 'Сыр', 'Курица', 'Грибы', 'Соус'],
    ingredientsKg: ['Камыр', 'Сыр', 'Тоок', 'Козу карын', 'Соус'],
    variants: [
      { label: '30 см', price: 590 },
      { label: '40 см', price: 790 },
    ],
  },
  {
    id: 74, category: 'fastfood',
    name: 'Пицца «Цезарь»', nameKg: 'Пицца «Цезарь»',
    description: 'Пицца Цезарь',
    descriptionKg: 'Цезарь пиццасы',
    image: './Меню/Цезарь пицца.webp',
    ingredients: ['Тесто', 'Сыр', 'Курица', 'Салат', 'Соус'],
    ingredientsKg: ['Камыр', 'Сыр', 'Тоок', 'Салат', 'Соус'],
    variants: [
      { label: '30 см', price: 570 },
      { label: '40 см', price: 770 },
    ],
  },
  {
    id: 75, category: 'fastfood',
    name: 'Рамен', nameKg: 'Рамён',
    description: 'Японский рамён',
    descriptionKg: 'Жапон рамёну',
    price: 260, image: './Меню/Рамен.jpeg',
    ingredients: ['Лапша', 'Бульон', 'Мясо', 'Овощи'],
    ingredientsKg: ['Лапша', 'Бульон', 'Эт', 'Жашылчалар'],
  },
  {
    id: 81, category: 'fastfood',
    name: 'Мини самсы', nameKg: 'Мини кум самсы',
    description: 'Мини песочные самсы',
    descriptionKg: 'Мини кум самсы',
    price: 55, image: './Меню/Мини.webp',
    ingredients: ['Тесто', 'Начинка'],
    ingredientsKg: ['Камыр', 'Начинка'],
  },
  {
    id: 86, category: 'fastfood',
    name: 'Пирог', nameKg: 'Пирог',
    description: 'Сочные самсы из слоёного теста',
    descriptionKg: 'Катмарлуу камырдан шырындуу самсы',
    price: 80, image: './Меню/Самсыы.webp',
    ingredients: ['Тесто', 'Мясо', 'Лук'],
    ingredientsKg: ['Камыр', 'Эт', 'Пияз'],
  },
  {
    id: 82, category: 'fastfood',
    name: 'Хлеб', nameKg: 'Нан',
    description: 'Свежий хлеб',
    descriptionKg: 'Жаңы нан',
    price: 45, image: './Меню/Хлеб.webp',
    ingredients: ['Мука', 'Вода', 'Дрожжи'],
    ingredientsKg: ['Ун', 'Суу', 'Ачыткы'],
  },
  {
    id: 83, category: 'fastfood',
    name: 'Чай', nameKg: 'Чай',
    description: 'Горячий чай',
    descriptionKg: 'Ысык чай',
    price: 20, image: './Меню/Чайй.jpeg',
    ingredients: ['Чай', 'Вода'],
    ingredientsKg: ['Чай', 'Суу'],
  },

  // ══════════════════════════════════════════════════════════════
  //  ДЕСЕРТЫ
  // ══════════════════════════════════════════════════════════════
  {
    id: 76, category: 'dessert',
    name: 'Сан-Себастьян', nameKg: 'Сан-Себастьян',
    description: 'Десерт Сан-Себастьян',
    descriptionKg: 'Сан-Себастьян десерти',
    image: './Меню/Сан-себа.webp',
    ingredients: ['Тесто', 'Крем', 'Фрукты'],
    ingredientsKg: ['Камыр', 'Крем', 'Жемиштер'],
    variants: [
      { label: 'Обычный',    price: 360, image: './Меню/Сан-себа.webp' },
      { label: 'Фисташковый', price: 390, image: './Меню/Фисташковый саба .webp' },
    ],
  },
  {
    id: 77, category: 'dessert',
    name: 'Чизкейк', nameKg: 'Чизкейк',
    description: 'Классический чизкейк',
    descriptionKg: 'Классикалык чизкейк',
    price: 370, image: './Меню/Чиз.webp',
    ingredients: ['Сыр', 'Тесто', 'Крем'],
    ingredientsKg: ['Сыр', 'Камыр', 'Крем'],
  },
  {
    id: 78, category: 'dessert',
    name: 'Три шоколада', nameKg: 'Үч шоколад',
    description: 'Торт три шоколада',
    descriptionKg: 'Үч шоколад торт',
    price: 280, image: './Меню/Три-шоколада.webp',
    ingredients: ['Шоколад', 'Тесто', 'Крем'],
    ingredientsKg: ['Шоколад', 'Камыр', 'Крем'],
  },
  {
    id: 79, category: 'dessert',
    name: 'Трайфл макс', nameKg: 'Трайфл макс',
    description: 'Десерт Трайфл макс',
    descriptionKg: 'Трайфл макс десерти',
    price: 290, image: './Меню/Трайфл .webp',
    ingredients: ['Бисквит', 'Крем', 'Фрукты'],
    ingredientsKg: ['Бисквит', 'Крем', 'Жемиштер'],
  },
  {
    id: 84, category: 'dessert',
    name: 'Боорсок + каймак', nameKg: 'Боорсок + каймак',
    description: 'Боорсок с каймаком',
    descriptionKg: 'Каймак менен боорсок',
    image: './Меню/Борсокк.webp',
    variants: [
      { label: '0.5 кг', price: 170 },
      { label: '1 кг',   price: 340 },
    ],
  },
];